#This file holds all constant variables that needs to be reused accross files
DARK = '#40514e'
PRIMARY = '#2f89fc'
SECONDAY = '#30e3ca'
BACKGROUND = '#f5f5f5'
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
MIN_PADDING = 4
MID_PADDING = 8
MAX_PADDING = 16
APP_TITLE = "PYTHON UI"
TOOLS_OPTION_ONE = "Conventional MCS"
TOOLS_OPTION_TWO = "ML Algorithm"
FILES_OPTION_ONE = "Open CSV"
FILES_OPTION_TWO = "Exit"

INDICES_OPTION_ONE = "HL-1"
INDICES_OPTION_TWO = "HL-2"
INDICES_SUB_OPTION_ONE = "Option-1"
INDICES_SUB_OPTION_TWO = "Option-2"
